import React from 'react';
import { Link } from 'react-router-dom';
import { 
  TrendingUp, 
  Coins, 
  BarChart3, 
  Landmark, 
  CreditCard, 
  Percent, 
  BadgeInfo,
  ArrowRight,
  PieChart,
  UserCheck,
  ArrowRightLeft,
  Gift,
  RefreshCcw,
  ShieldCheck,
  Zap,
  Activity,
  Briefcase,
  Shield,
  Building,
  Target,
  Globe,
  Calendar,
  ArrowUpRight
} from 'lucide-react';
import { motion } from 'motion/react';

const CATEGORIES = [
  {
    name: 'Wealth Management',
    id: 'wealth',
    cards: [
      { title: 'SIP Manager', description: 'Systematic investment planning with precise compound return logic.', path: '/calculators/sip', icon: TrendingUp, color: 'text-blue-500' },
      { title: 'Investment CAGR', description: 'Determine the geometric progression of your assets over time.', path: '/calculators/cagr', icon: Target, color: 'text-emerald-500' },
      { title: 'Mutual Funds', description: 'Analyze performance metrics and projected absolute returns.', path: '/calculators/mutual-fund', icon: PieChart, color: 'text-cyan-500' },
      { title: 'Lumpsum Growth', description: 'Project future values of one-time capital injections.', path: '/calculators/lumpsum', icon: BarChart3, color: 'text-indigo-500' },
      { title: 'Dividend Yield', description: 'Analyze passive income generated by stock portfolios.', path: '/calculators/dividend-yield', icon: Coins, color: 'text-amber-500' },
      { title: 'Retirement Pot', description: 'Architect your post-career financial state with inflation modeling.', path: '/calculators/retirement', icon: Coins, color: 'text-purple-500' },
    ]
  },
  {
    name: 'Debt & Credit',
    id: 'debt',
    cards: [
      { title: 'Debt Snowball', description: 'Eliminate debt systematically targeting small balances first.', path: '/calculators/debt-snowball', icon: Zap, color: 'text-orange-500' },
      { title: 'CC Payoff', description: 'Simulate credit card liquidation and interest drain analysis.', path: '/calculators/credit-card-payoff', icon: CreditCard, color: 'text-rose-500' },
      { title: 'Mortgage / Home', description: 'Professional-grade home loan amortization scheduling.', path: '/calculators/mortgage', icon: Landmark, color: 'text-slate-500' },
      { title: 'EMI Engine', description: 'Universal Equated Monthly Installment tool for all loans.', path: '/calculators/emi', icon: CreditCard, color: 'text-indigo-500' },
      { title: 'Auto Loan', description: 'Finance modeling for vehicle acquisitions with tax logic.', path: '/calculators/auto-loan', icon: CreditCard, color: 'text-blue-500' },
      { title: 'Student Debt', description: 'Plan for education costs with grace period adjustments.', path: '/calculators/student-loan', icon: Landmark, color: 'text-emerald-500' },
    ]
  },
  {
    name: 'Insurance & Protection',
    id: 'insurance',
    cards: [
      { title: 'HLV Calculator', description: 'Quantify your economic value and ideal coverage needs.', path: '/calculators/hlv', icon: Activity, color: 'text-rose-500' },
      { title: 'Term Life', description: 'Plan for long-term family security with term insurance.', path: '/calculators/term-insurance', icon: Shield, color: 'text-blue-500' },
      { title: 'Health Guard', description: 'Analyze health premium costs vs benefit coverage.', path: '/calculators/health-insurance', icon: ShieldCheck, color: 'text-emerald-500' },
    ]
  },
  {
    name: 'Business & Yield',
    id: 'business',
    cards: [
      { title: 'Break-Even Point', description: 'Determine the neutrality point for new business products.', path: '/calculators/break-even', icon: Target, color: 'text-indigo-500' },
      { title: 'Rental ROI', description: 'Evaluate real estate profitability and net rental yields.', path: '/calculators/rental-yield', icon: Building, color: 'text-cyan-500' },
      { title: 'Gratuity Pot', description: 'Calculate statutory retirement benefits based on tenure.', path: '/calculators/gratuity', icon: Gift, color: 'text-sky-500' },
    ]
  },
  {
    name: 'Global Taxes',
    id: 'taxes',
    cards: [
      { title: 'Income Tax', description: 'Compare regimes for USA, UK, India, and European zones.', path: '/calculators/income-tax', icon: Percent, color: 'text-orange-500' },
      { title: 'GST / VAT', description: 'Calculate transaction taxes based on multi-country rates.', path: '/calculators/gst', icon: ShieldCheck, color: 'text-indigo-500' },
      { title: 'Tax Guides', description: 'Local logic for 12+ jurisdictions and tax boundaries.', path: '/tax-guides', icon: Globe, color: 'text-emerald-500' },
    ]
  }
];

const ALL_CARDS = CATEGORIES.flatMap(cat => cat.cards);

interface NewsArticle {
  title: string;
  summary: string;
  date: string;
  category: string;
  image: string;
}

const NEWS_ARTICLES: NewsArticle[] = [
  {
    title: "Global Markets React to Shifting Interest Rate Projections",
    summary: "Central banks signal a potential pivot in monetary policy as inflation metrics stabilize across major economic zones.",
    date: "May 14, 2026",
    category: "Markets",
    image: "https://images.unsplash.com/photo-1611974717482-98ea0519302c?auto=format&fit=crop&q=80&w=800&fm=webp"
  },
  {
    title: "Tech Giants Unveil New AI Infrastructure Commitments",
    summary: "Silicon Valley leaders announce multi-billion dollar investments in quantum-ready data centers to power the next generation of LLMs.",
    date: "May 13, 2026",
    category: "Technology",
    image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&q=80&w=800&fm=webp"
  },
  {
    title: "The Rise of Sustainable Finance in Emerging Markets",
    summary: "New regulatory frameworks are accelerating the adoption of ESG-linked bonds in Southeast Asia and Latin America.",
    date: "May 12, 2026",
    category: "Economy",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=800&fm=webp"
  }
];

function NewsCard({ article }: { article: NewsArticle }) {
  return (
    <motion.div 
      initial={{ opacity: 0, y: 20 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true }}
      className="group relative bg-white/[0.02] border border-white/5 rounded-3xl overflow-hidden hover:border-[#0055FF]/30 transition-all duration-500"
    >
      <div className="aspect-[16/9] overflow-hidden relative">
        <img 
          src={article.image} 
          alt={article.title}
          className="w-full h-full object-cover grayscale opacity-50 group-hover:grayscale-0 group-hover:opacity-80 group-hover:scale-105 transition-all duration-700"
          referrerPolicy="no-referrer"
          loading="lazy"
          width="400"
          height="225"
        />
        <div className="absolute top-4 left-4">
          <span className="px-3 py-1 bg-black/60 backdrop-blur-md rounded-full text-[8px] font-black text-[#0055FF] uppercase tracking-tighter border border-white/5">
            {article.category}
          </span>
        </div>
      </div>
      
      <div className="p-6 space-y-4">
        <div className="space-y-2">
          <h3 className="text-xl font-display font-medium text-white tracking-tighter leading-tight group-hover:text-[#0055FF] transition-colors duration-500">
            {article.title}
          </h3>
          <p className="text-sm text-white/40 leading-relaxed line-clamp-2">
            {article.summary}
          </p>
        </div>
        
        <div className="pt-4 flex items-center justify-between border-t border-white/[0.05]">
           <div className="flex items-center gap-2">
              <Calendar className="w-3 h-3 text-white/20" />
              <span className="text-[10px] text-white/20 font-bold uppercase tracking-widest">{article.date}</span>
           </div>
           <button className="flex items-center gap-2 text-[10px] font-bold text-[#0055FF] uppercase tracking-widest group-hover:translate-x-1 transition-transform">
             Read Full Report <ArrowUpRight className="w-3 h-3" />
           </button>
        </div>
      </div>
    </motion.div>
  );
}
export default function Dashboard() {
  return (
    <div className="space-y-16 pb-16">
      <header className="space-y-6">
        <div className="flex items-center gap-3 mb-2">
          <div className="h-[1px] w-12 bg-[#0055FF]"></div>
          <span className="text-[9px] font-black text-[#0055FF] uppercase tracking-[0.5em]">Orbit Wealth Pro — Global Fintech Engine</span>
        </div>
        <h1 className="text-4xl sm:text-5xl md:text-7xl font-display font-medium text-white tracking-tighter leading-[1.1]">
          Financial <br />
          <span className="text-white/10">Dashboard.</span>
        </h1>
        <p className="text-white/40 max-w-xl text-sm md:text-base font-light leading-relaxed">
          Access Orbit Wealth Pro's suite of institutional-grade financial tools. 
          Precision engineering for the modern global investor.
        </p>
      </header>

      <section className="space-y-10">
        <div className="flex items-center gap-4">
           <h2 className="text-[10px] font-bold text-white/20 uppercase tracking-[0.4em]">Integrated Computation Suite</h2>
           <div className="flex-1 h-px bg-white/[0.03]"></div>
        </div>
        
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 md:gap-6">
          {ALL_CARDS.map((card, idx) => (
            <motion.div
              key={card.path}
              initial={idx < 6 ? { opacity: 1, y: 0 } : { opacity: 0, y: 20 }}
              whileInView={idx >= 6 ? { opacity: 1, y: 0 } : undefined}
              viewport={{ once: true, margin: "-50px" }}
              transition={{ delay: idx < 6 ? 0 : 0.1, duration: 0.4 }}
            >
              <Link 
                to={card.path}
                className="group block p-[15px] md:p-8 bg-white/[0.01] border border-white/[0.04] rounded-[1.5rem] md:rounded-[2rem] hover:bg-white/[0.02] hover:border-[#0055FF]/30 transition-all duration-700 h-full relative overflow-hidden"
              >
                <div className="absolute top-0 right-0 p-4 opacity-0 group-hover:opacity-100 transition-opacity">
                  <ArrowRight className="w-4 h-4 text-[#0055FF]" />
                </div>
                
                <div className="space-y-6">
                  <div className={`w-10 h-10 rounded-xl flex items-center justify-center border border-white/5 bg-white/[0.02] ${card.color}`}>
                    <card.icon className="w-4 h-4" />
                  </div>
                  
                  <div className="space-y-2">
                    <h3 className="text-xl font-display font-medium text-white group-hover:text-[#0055FF] transition-colors duration-500">
                      {card.title}
                    </h3>
                    <p className="text-xs text-white/30 leading-relaxed font-light line-clamp-2">
                      {card.description}
                    </p>
                  </div>
                </div>
              </Link>
            </motion.div>
          ))}
        </div>
      </section>

      {/* Global Finance News Section */}
      <section className="space-y-10 pt-16">
        <div className="flex items-center gap-4">
           <h2 className="text-[10px] font-bold text-[#0055FF] uppercase tracking-[0.4em]">Global Finance News</h2>
           <div className="flex-1 h-px bg-[#0055FF]/10"></div>
           <div className="flex items-center gap-2 text-[8px] font-bold text-white/20 uppercase tracking-widest">
             <div className="w-1 h-1 rounded-full bg-[#0055FF] animate-pulse"></div>
             Live Updates
           </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 md:gap-6">
          {NEWS_ARTICLES.map((article, idx) => (
            <NewsCard key={idx} article={article} />
          ))}
        </div>
        
        <div className="flex justify-center pt-4">
          <button className="px-8 py-3 bg-white/[0.02] border border-white/5 rounded-full text-[10px] font-bold text-white/40 uppercase tracking-widest hover:bg-[#0055FF]/10 hover:border-[#0055FF]/30 hover:text-white transition-all cursor-pointer">
            Explore All Market Insights
          </button>
        </div>
      </section>

      <section className="pt-24 border-t border-white/[0.05] grid grid-cols-1 md:grid-cols-2 gap-12 items-center">
        <div className="space-y-4">
          <h2 className="text-2xl font-display font-medium">Built for accuracy.</h2>
          <p className="text-sm text-white/30 leading-relaxed max-w-md">
            Our engine accounts for localized interest compounding, tax thresholds, and currency fluctuations to ensure your planning is based on high-integrity data.
          </p>
        </div>
        <div className="flex gap-12">
           <div className="space-y-1">
             <div className="text-4xl font-display text-white">100%</div>
             <div className="text-[9px] text-white/20 uppercase font-bold tracking-[0.2em]">Computation Accuracy</div>
           </div>
           <div className="space-y-1">
             <div className="text-4xl font-display text-white">Instant</div>
             <div className="text-[9px] text-white/20 uppercase font-bold tracking-[0.2em]">Execution Latency</div>
           </div>
        </div>
      </section>
    </div>
  );
}
