import React from 'react';
import { Link } from 'react-router-dom';
import { 
  TrendingUp, 
  Coins, 
  BarChart3, 
  Landmark, 
  CreditCard, 
  Percent, 
  BadgeInfo,
  ArrowRight,
  PieChart,
  UserCheck,
  ArrowRightLeft,
  Gift,
  RefreshCcw,
  ShieldCheck,
  Zap,
  Activity,
  Briefcase,
  Shield,
  Building,
  Target,
  Globe
} from 'lucide-react';
import { motion } from 'motion/react';

const CATEGORIES = [
  {
    name: 'Wealth Management',
    id: 'wealth',
    cards: [
      { title: 'SIP Manager', description: 'Systematic investment planning with precise compound return logic.', path: '/calculators/sip', icon: TrendingUp, color: 'text-blue-500' },
      { title: 'Investment CAGR', description: 'Determine the geometric progression of your assets over time.', path: '/calculators/cagr', icon: Target, color: 'text-emerald-500' },
      { title: 'Mutual Funds', description: 'Analyze performance metrics and projected absolute returns.', path: '/calculators/mutual-fund', icon: PieChart, color: 'text-cyan-500' },
      { title: 'Lumpsum Growth', description: 'Project future values of one-time capital injections.', path: '/calculators/lumpsum', icon: BarChart3, color: 'text-indigo-500' },
      { title: 'Dividend Yield', description: 'Analyze passive income generated by stock portfolios.', path: '/calculators/dividend-yield', icon: Coins, color: 'text-amber-500' },
      { title: 'Retirement Pot', description: 'Architect your post-career financial state with inflation modeling.', path: '/calculators/retirement', icon: Coins, color: 'text-purple-500' },
    ]
  },
  {
    name: 'Debt & Credit',
    id: 'debt',
    cards: [
      { title: 'Debt Snowball', description: 'Eliminate debt systematically targeting small balances first.', path: '/calculators/debt-snowball', icon: Zap, color: 'text-orange-500' },
      { title: 'CC Payoff', description: 'Simulate credit card liquidation and interest drain analysis.', path: '/calculators/credit-card-payoff', icon: CreditCard, color: 'text-rose-500' },
      { title: 'Mortgage / Home', description: 'Professional-grade home loan amortization scheduling.', path: '/calculators/mortgage', icon: Landmark, color: 'text-slate-500' },
      { title: 'EMI Engine', description: 'Universal Equated Monthly Installment tool for all loans.', path: '/calculators/emi', icon: CreditCard, color: 'text-indigo-500' },
      { title: 'Auto Loan', description: 'Finance modeling for vehicle acquisitions with tax logic.', path: '/calculators/auto-loan', icon: CreditCard, color: 'text-blue-500' },
      { title: 'Student Debt', description: 'Plan for education costs with grace period adjustments.', path: '/calculators/student-loan', icon: Landmark, color: 'text-emerald-500' },
    ]
  },
  {
    name: 'Insurance & Protection',
    id: 'insurance',
    cards: [
      { title: 'HLV Calculator', description: 'Quantify your economic value and ideal coverage needs.', path: '/calculators/hlv', icon: Activity, color: 'text-rose-500' },
      { title: 'Term Life', description: 'Plan for long-term family security with term insurance.', path: '/calculators/term-insurance', icon: Shield, color: 'text-blue-500' },
      { title: 'Health Guard', description: 'Analyze health premium costs vs benefit coverage.', path: '/calculators/health-insurance', icon: ShieldCheck, color: 'text-emerald-500' },
    ]
  },
  {
    name: 'Business & Yield',
    id: 'business',
    cards: [
      { title: 'Break-Even Point', description: 'Determine the neutrality point for new business products.', path: '/calculators/break-even', icon: Target, color: 'text-indigo-500' },
      { title: 'Rental ROI', description: 'Evaluate real estate profitability and net rental yields.', path: '/calculators/rental-yield', icon: Building, color: 'text-cyan-500' },
      { title: 'Gratuity Pot', description: 'Calculate statutory retirement benefits based on tenure.', path: '/calculators/gratuity', icon: Gift, color: 'text-sky-500' },
    ]
  },
  {
    name: 'Global Taxes',
    id: 'taxes',
    cards: [
      { title: 'Income Tax', description: 'Compare regimes for USA, UK, India, and European zones.', path: '/calculators/income-tax', icon: Percent, color: 'text-orange-500' },
      { title: 'GST / VAT', description: 'Calculate transaction taxes based on multi-country rates.', path: '/calculators/gst', icon: ShieldCheck, color: 'text-indigo-500' },
      { title: 'Tax Guides', description: 'Local logic for 12+ jurisdictions and tax boundaries.', path: '/tax-guides', icon: Globe, color: 'text-emerald-500' },
    ]
  }
];

const ALL_CARDS = CATEGORIES.flatMap(cat => cat.cards);

export default function Dashboard() {
  return (
    <div className="space-y-24 py-16">
      <header className="space-y-8">
        <div className="flex items-center gap-3 mb-2">
          <div className="h-[1px] w-12 bg-[#0055FF]"></div>
          <span className="text-[9px] font-black text-[#0055FF] uppercase tracking-[0.5em]">Orbit Wealth Pro</span>
        </div>
        <h1 className="text-6xl md:text-8xl font-display font-medium text-white tracking-tighter leading-[0.85]">
          Wealth <br />
          <span className="text-white/10">Computation.</span>
        </h1>
        <p className="text-white/40 max-w-2xl text-lg font-light leading-relaxed">
          Access Orbit Wealth Pro's suite of institutional-grade financial tools. 
          Precision engineering for the modern global investor.
        </p>
      </header>

      <section className="space-y-12">
        <div className="flex items-center gap-4">
           <h2 className="text-[10px] font-bold text-white/20 uppercase tracking-[0.4em]">Integrated Computation Suite</h2>
           <div className="flex-1 h-px bg-white/[0.03]"></div>
        </div>
        
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {ALL_CARDS.map((card, idx) => (
            <motion.div
              key={card.path}
              initial={{ opacity: 0, y: 15 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: idx * 0.01, ease: [0.23, 1, 0.32, 1] }}
            >
              <Link 
                to={card.path}
                className="group block p-8 bg-white/[0.01] border border-white/[0.04] rounded-[2rem] hover:bg-white/[0.02] hover:border-[#0055FF]/30 transition-all duration-700 h-full relative overflow-hidden"
              >
                <div className="absolute top-0 right-0 p-4 opacity-0 group-hover:opacity-100 transition-opacity">
                  <ArrowRight className="w-4 h-4 text-[#0055FF]" />
                </div>
                
                <div className="space-y-6">
                  <div className={`w-10 h-10 rounded-xl flex items-center justify-center border border-white/5 bg-white/[0.02] ${card.color}`}>
                    <card.icon className="w-4 h-4" />
                  </div>
                  
                  <div className="space-y-2">
                    <h3 className="text-xl font-display font-medium text-white group-hover:text-[#0055FF] transition-colors duration-500">
                      {card.title}
                    </h3>
                    <p className="text-xs text-white/30 leading-relaxed font-light line-clamp-2">
                      {card.description}
                    </p>
                  </div>
                </div>
              </Link>
            </motion.div>
          ))}
        </div>
      </section>

      <section className="pt-24 border-t border-white/[0.05] grid grid-cols-1 md:grid-cols-2 gap-12 items-center">
        <div className="space-y-4">
          <h2 className="text-2xl font-display font-medium">Built for accuracy.</h2>
          <p className="text-sm text-white/30 leading-relaxed max-w-md">
            Our engine accounts for localized interest compounding, tax thresholds, and currency fluctuations to ensure your planning is based on high-integrity data.
          </p>
        </div>
        <div className="flex gap-12">
           <div className="space-y-1">
             <div className="text-4xl font-display text-white">100%</div>
             <div className="text-[9px] text-white/20 uppercase font-bold tracking-[0.2em]">Computation Accuracy</div>
           </div>
           <div className="space-y-1">
             <div className="text-4xl font-display text-white">Instant</div>
             <div className="text-[9px] text-white/20 uppercase font-bold tracking-[0.2em]">Execution Latency</div>
           </div>
        </div>
      </section>
    </div>
  );
}
