import React from 'react';
import { Link } from 'react-router-dom';
import { 
  TrendingUp, 
  Coins, 
  BarChart3, 
  Landmark, 
  CreditCard, 
  Percent, 
  BadgeInfo,
  ArrowRight,
  PieChart,
  UserCheck,
  ArrowRightLeft,
  Gift,
  RefreshCcw,
  ShieldCheck,
  Zap,
  Activity,
  Briefcase,
  Shield,
  Building,
  Target,
  Globe,
  Calendar,
  ArrowUpRight,
  X,
  Home
} from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import MarketTicker from './MarketTicker';
import WealthIntelligenceBlock from './WealthIntelligenceBlock';
import BlogPreview from './BlogPreview';
import WealthMilestones from './WealthMilestones';
import { Goal } from '../types';

const INITIAL_GOALS: Goal[] = [
  {
    id: 'fire',
    title: 'Retire Early (FIRE Plan)',
    subtitle: 'Financial Independence Architecture',
    icon: <TrendingUp className="w-6 h-6" />,
    target: 2500000,
    current: 450000,
    years: 15,
    annualReturn: 0.08,
    color: 'emerald',
    accent: '#10b981'
  },
  {
    id: 'real-estate',
    title: 'Acquire Real Estate',
    subtitle: 'Strategic Property Portfolio',
    icon: <Home className="w-6 h-6" />,
    target: 800000,
    current: 125000,
    years: 5,
    annualReturn: 0.04,
    color: 'amber',
    accent: '#f59e0b'
  },
  {
    id: 'emergency',
    title: 'Emergency Fund',
    subtitle: 'Liquidity & Risk Mitigation',
    icon: <Shield className="w-6 h-6" />,
    target: 50000,
    current: 35000,
    years: 2,
    annualReturn: 0.02,
    color: 'sky',
    accent: '#0ea5e9'
  }
];

const CATEGORIES = [
  {
    name: 'Wealth Management',
    id: 'wealth',
    cards: [
      { title: 'SIP Manager', description: 'Systematic investment planning with precise compound return logic.', path: '/calculators/sip', icon: TrendingUp, color: 'text-blue-500' },
      { title: 'Investment CAGR', description: 'Determine the geometric progression of your assets over time.', path: '/calculators/cagr', icon: Target, color: 'text-emerald-500' },
      { title: 'Mutual Funds', description: 'Analyze performance metrics and projected absolute returns.', path: '/calculators/mutual-fund', icon: PieChart, color: 'text-cyan-500' },
      { title: 'Lumpsum Growth', description: 'Project future values of one-time capital injections.', path: '/calculators/lumpsum', icon: BarChart3, color: 'text-indigo-500' },
      { title: 'Dividend Yield', description: 'Analyze passive income generated by stock portfolios.', path: '/calculators/dividend-yield', icon: Coins, color: 'text-amber-500' },
      { title: 'Retirement Pot', description: 'Architect your post-career financial state with inflation modeling.', path: '/calculators/retirement', icon: Coins, color: 'text-purple-500' },
      { title: 'Forex Converter', description: 'Real-time exchange engine for global currency pairs.', path: '/calculators/currency-converter', icon: RefreshCcw, color: 'text-rose-500' },
    ]
  },
  {
    name: 'Debt & Credit',
    id: 'debt',
    cards: [
      { title: 'Debt Snowball', description: 'Eliminate debt systematically targeting small balances first.', path: '/calculators/debt-snowball', icon: Zap, color: 'text-orange-500' },
      { title: 'CC Payoff', description: 'Simulate credit card liquidation and interest drain analysis.', path: '/calculators/credit-card-payoff', icon: CreditCard, color: 'text-rose-500' },
      { title: 'Mortgage / Home', description: 'Professional-grade home loan amortization scheduling.', path: '/calculators/mortgage', icon: Landmark, color: 'text-slate-500' },
      { title: 'EMI Engine', description: 'Universal Equated Monthly Installment tool for all loans.', path: '/calculators/emi', icon: CreditCard, color: 'text-indigo-500' },
      { title: 'Auto Loan', description: 'Finance modeling for vehicle acquisitions with tax logic.', path: '/calculators/auto-loan', icon: CreditCard, color: 'text-blue-500' },
      { title: 'Student Debt', description: 'Plan for education costs with grace period adjustments.', path: '/calculators/student-loan', icon: Landmark, color: 'text-emerald-500' },
      { title: 'Loan Transfer', description: 'Optimize your interest drain with mortgage balance transfers.', path: '/calculators/home-loan-transfer', icon: ArrowRightLeft, color: 'text-sky-500' },
    ]
  },
  {
    name: 'Insurance & Protection',
    id: 'insurance',
    cards: [
      { title: 'HLV Calculator', description: 'Quantify your economic value and ideal coverage needs.', path: '/calculators/hlv', icon: ShieldCheck, color: 'text-rose-500' },
      { title: 'Term Life', description: 'Plan for long-term family security with term insurance.', path: '/calculators/term-insurance', icon: Shield, color: 'text-blue-500' },
      { title: 'Health Guard', description: 'Analyze health premium costs vs benefit coverage.', path: '/calculators/health-insurance', icon: ShieldCheck, color: 'text-emerald-500' },
    ]
  },
  {
    name: 'Business & Yield',
    id: 'business',
    cards: [
      { title: 'Break-Even Point', description: 'Determine the neutrality point for new business products.', path: '/calculators/break-even', icon: Target, color: 'text-indigo-500' },
      { title: 'Rental ROI', description: 'Evaluate real estate profitability and net rental yields.', path: '/calculators/rental-yield', icon: Building, color: 'text-cyan-500' },
      { title: 'Gratuity Pot', description: 'Calculate statutory retirement benefits based on tenure.', path: '/calculators/gratuity', icon: Gift, color: 'text-sky-500' },
    ]
  },
  {
    name: 'Global Taxes',
    id: 'taxes',
    cards: [
      { title: 'Income Tax', description: 'Compare regimes for USA, UK, India, and European zones.', path: '/calculators/income-tax', icon: Percent, color: 'text-orange-500' },
      { title: 'GST / VAT', description: 'Calculate transaction taxes based on multi-country rates.', path: '/calculators/gst', icon: ShieldCheck, color: 'text-indigo-500' },
      { title: 'Tax Guides', description: 'Local logic for 12+ jurisdictions and tax boundaries.', path: '/tax-guides', icon: Globe, color: 'text-emerald-500' },
    ]
  }
];

const ALL_CARDS = CATEGORIES.flatMap(cat => cat.cards);

interface NewsArticle {
  id: string;
  title: string;
  summary: string;
  content: string;
  date: string;
  category: string;
  image: string;
}

const NEWS_ARTICLES: NewsArticle[] = [
  {
    id: "fed-rates-2026",
    title: "Global Markets React to Shifting Interest Rate Projections",
    summary: "Central banks signal a potential pivot in monetary policy as inflation metrics stabilize across major economic zones.",
    content: "Institutional investors are recalibrating their portfolios as the Federal Reserve and the European Central Bank signal a potential easing of monetary constraints. After a prolonged period of aggressive rate hikes, inflationary pressures have finally shown signs of durable stabilization. Market analysts suggest that while the 'higher for longer' narrative dominated early 2026, the second half of the year may witness the first set of coordinated rate cuts in nearly three years. This shift has triggered a massive rotation into growth stocks and emerging market bonds, which have been under pressure. However, some economists warn that a premature pivot could reignite price volatility, especially with energy costs remaining sensitive to geopolitical shifts in the Middle East and Eastern Europe.",
    date: "May 14, 2026",
    category: "Markets",
    image: "https://images.unsplash.com/photo-1611974717482-98ea0519302c?auto=format&fit=crop&q=80&w=800&fm=webp"
  },
  {
    id: "ai-infra-commit",
    title: "Tech Giants Unveil New AI Infrastructure Commitments",
    summary: "Silicon Valley leaders announce multi-billion dollar investments in quantum-ready data centers to power the next generation of LLMs.",
    content: "The race for AI supremacy has entered a new hardware-centric phase. Major technology conglomerates have announced a combined $120 billion commitment toward building 'Quantum-Ready' data centers across Northern Europe and the United States. These facilities are designed not just for current generative models, but for the anticipated integration of quantum computing processors. This infrastructure surge is expected to drive significant demand for specialized semiconductors and renewable energy solutions. Energy providers are already seeing a spike in long-term power purchase agreements as tech firms strive to keep their AI ambitions carbon-neutral. Investors are closely watching the utilities sector as it becomes a secondary play on the AI boom.",
    date: "May 13, 2026",
    category: "Technology",
    image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&q=80&w=800&fm=webp"
  },
  {
    id: "sustainable-finance-rise",
    title: "The Rise of Sustainable Finance in Emerging Markets",
    summary: "New regulatory frameworks are accelerating the adoption of ESG-linked bonds in Southeast Asia and Latin America.",
    content: "Sustainability is no longer a Western-centric theme in the financial markets. Emerging markets, particularly in Southeast Asia and Latin America, are witnessing a record surge in ESG (Environmental, Social, and Governance) bond issuances. Governments in these regions have introduced new transparency mandates and tax incentives for green infrastructure projects. This regulatory clarity has attracted institutional capital from global pension funds looking for diversified impact investments. Analysts predict that green finance will account for nearly 25% of all corporate debt issuance in these regions by the end of 2027. This transition is not without challenges, as 'greenwashing' concerns remain a primary hurdle for smaller credit issuers.",
    date: "May 12, 2026",
    category: "Economy",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=800&fm=webp"
  },
  {
    id: "real-estate-yields-2026",
    title: "Real Estate Global Trends: A Shift Toward Specialized Assets",
    summary: "Institutional property investors are pivoting away from traditional office spaces toward logistics and life sciences hubs.",
    content: "The global real estate market is undergoing a structural transformation. With remote work remaining a persistent feature of the modern workforce, traditional office vacancies in major financial hubs like New York, London, and Tokyo continue to hover at record highs. In response, professional property managers are aggressively pivoting toward 'alternative' real estate assets. Logistics centers, cold storage facilities, and life-sciences laboratory spaces are seeing unprecedented capital inflows. These assets offer higher yields and lower vacancy risks compared to commercial office space. Additionally, the rise of purpose-built student accommodation is becoming a favored hedge against economic cycles, providing stable cash flows for long-term institutional holders.",
    date: "May 11, 2026",
    category: "Real Estate",
    image: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&q=80&w=800&fm=webp"
  },
  {
    id: "crypto-regulation-2026",
    title: "Comprehensive Digital Asset Regulations Nearing Final Vote",
    summary: "Regulatory bodies prepare to implement harmonized rules for stablecoins and institutional crypto custody solutions.",
    content: "The long-awaited 'Global Digital Asset Framework' (GDAF) is nearing a final vote in the European Parliament and the US Congress simultaneously. These harmonized rules aim to provide a clear legal footing for stablecoin issuers and bank-grade crypto custody providers. By mandating full reserve disclosures and strict liquidity buffers, the framework seeks to prevent the systemic failures seen in previous cycles. Institutional adoption is expected to accelerate significantly once these rules are in place, as traditional hedge funds and insurance firms seek regulated avenues for crypto exposure. The focus on 'Smart Contracts' integration within traditional finance—'tokenized real-world assets'—is cited as the primary growth engine for the next decade.",
    date: "May 10, 2026",
    category: "Crypto",
    image: "https://images.unsplash.com/photo-1621761191319-c6fb62004040?auto=format&fit=crop&q=80&w=800&fm=webp"
  },
  {
    id: "gold-safety-2026",
    title: "Gold Values Surge Amid Geopolitical Portfolio Hedging",
    summary: "Precious metals reach multi-year highs as central banks increase physical reserves amid global uncertainty.",
    content: "Gold continues to solidify its role as the ultimate 'safe haven' in a fractured global landscape. Central banks in China, India, and Turkey have significantly increased their physical gold reserves over the first quarter of 2026, citing a desire to diversify away from traditional reserve currencies. This institutional buying spree, coupled with persistent geopolitical tensions, has pushed gold prices to record levels. Retail demand for physical bullion is also rising as individual investors look for inflation hedges that exist outside the digital and banking ecosystems. Analysts suggest that even if interest rates begin to fall, the demand for gold and other precious metals will remain robust as long as trade fragmentation and diplomatic friction persist.",
    date: "May 09, 2026",
    category: "Precious Metals",
    image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&q=80&w=800&fm=webp"
  }
];

const NewsModal: React.FC<{ article: NewsArticle; onClose: () => void }> = ({ article, onClose }) => {
  if (!article) return null;

  return (
    <motion.div 
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="fixed inset-0 z-[100] flex items-center justify-center p-4 md:p-8 bg-[#0B1221]/95 backdrop-blur-2xl"
    >
      <motion.div 
        initial={{ opacity: 0, scale: 0.9, y: 20 }}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        exit={{ opacity: 0, scale: 0.9, y: 20 }}
        className="relative bg-[#111827] border border-white/10 rounded-[2rem] max-w-4xl w-full max-h-[90vh] overflow-hidden flex flex-col shadow-2xl shadow-black"
      >
        <button 
          onClick={onClose}
          className="absolute top-6 right-6 z-10 p-2 bg-black/40 hover:bg-black/60 rounded-full border border-white/10 text-white/70 hover:text-white transition-all"
        >
          <X className="w-5 h-5" />
        </button>

        <div className="overflow-y-auto custom-scrollbar">
          <div className="aspect-video w-full relative">
            <img 
              src={article.image} 
              alt={article.title}
              className="w-full h-full object-cover"
              referrerPolicy="no-referrer"
              loading="lazy"
            />
            <div className="absolute inset-0 bg-gradient-to-t from-[#111827] via-transparent to-transparent"></div>
            <div className="absolute bottom-8 left-8 right-8">
              <span className="px-3 py-1 bg-[#f59e0b] rounded-full text-base font-black text-black uppercase tracking-widest mb-4 inline-block">
                {article.category}
              </span>
                  <h2 className="text-5xl md:text-7xl font-display font-medium text-[#f59e0b] tracking-tighter leading-tight">
                    {article.title}
                  </h2>
            </div>
          </div>

          <div className="p-8 md:p-12 space-y-8">
            <div className="flex items-center gap-6 border-b border-white/5 pb-8">
              <div className="flex items-center gap-2">
                <Calendar className="w-4 h-4 text-white/70" />
                <span className="text-base text-slate-200 font-bold uppercase tracking-widest">{article.date}</span>
              </div>
              <div className="flex items-center gap-2">
                <UserCheck className="w-4 h-4 text-white/70" />
                <span className="text-base text-slate-200 font-bold uppercase tracking-widest">Orbit Research Team</span>
              </div>
            </div>

            <div className="space-y-6">
              <p className="text-3xl text-slate-100 font-medium leading-relaxed italic border-l-4 border-[#f59e0b] pl-6">
                {article.summary}
              </p>
              <div className="text-2xl text-slate-200 leading-relaxed font-light space-y-6">
                {article.content.split('. ').map((sentence, i) => (
                  <p key={i}>{sentence}.</p>
                ))}
              </div>
            </div>

            <div className="pt-12 border-t border-white/5 flex flex-col md:flex-row gap-8 justify-between items-center">
              <div className="text-base text-white/70 uppercase tracking-[0.2em] font-bold">
                © 2026 ORBIT WEALTH PRO — All Rights Reserved
              </div>
              <button 
                onClick={onClose}
                className="px-10 py-4 bg-[#f59e0b] text-black font-black text-base uppercase tracking-[0.2em] rounded-full hover:scale-105 transition-transform"
              >
                Return to Intelligence Suite
              </button>
            </div>
          </div>
        </div>
      </motion.div>
    </motion.div>
  );
};

const NewsCard: React.FC<{ article: NewsArticle; onReadMore: (article: NewsArticle) => void }> = ({ article, onReadMore }) => {
  return (
    <motion.div 
      initial={{ opacity: 0, y: 20 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true }}
      className="group relative bg-white/[0.03] backdrop-blur-md border border-white/5 rounded-2xl overflow-hidden hover:border-[#f59e0b]/30 transition-all duration-500"
    >
      <div className="aspect-[16/9] overflow-hidden relative">
        <img 
          src={article.image} 
          alt={article.title}
          className="w-full h-full object-cover grayscale opacity-50 group-hover:grayscale-0 group-hover:opacity-80 group-hover:scale-105 transition-all duration-700"
          referrerPolicy="no-referrer"
          loading="lazy"
          width="400"
          height="225"
        />
        <div className="absolute top-4 left-4">
          <span className="px-3 py-1 bg-black/60 backdrop-blur-md rounded-full text-sm font-black text-[#f59e0b] uppercase tracking-tighter border border-white/5">
            {article.category}
          </span>
        </div>
      </div>
      
      <div className="p-6 space-y-4">
        <div className="space-y-2">
          <h3 className="text-3xl font-display font-bold text-[#f59e0b] tracking-tighter leading-tight group-hover:scale-[1.02] origin-left transition-transform duration-500">
            {article.title}
          </h3>
          <p className="text-lg text-slate-100 leading-relaxed line-clamp-2 font-medium">
            {article.summary}
          </p>
        </div>
        
        <div className="pt-4 flex items-center justify-between border-t border-white/[0.05]">
           <div className="flex items-center gap-2">
              <Calendar className="w-3 h-3 text-white/70" />
              <span className="text-base text-slate-200 font-bold uppercase tracking-widest">{article.date}</span>
           </div>
           <button 
             onClick={() => onReadMore(article)}
             aria-label={`Read full report: ${article.title}`}
             className="flex items-center gap-2 text-base font-bold text-[#f59e0b] uppercase tracking-widest group-hover:translate-x-1 transition-transform cursor-pointer outline-none focus:underline"
           >
             Read Full Report <ArrowUpRight className="w-3 h-3" />
           </button>
        </div>
      </div>
    </motion.div>
  );
}

export default function Dashboard() {
  const [selectedArticle, setSelectedArticle] = React.useState<NewsArticle | null>(null);
  const [showAllNews, setShowAllNews] = React.useState(false);
  const [goals, setGoals] = React.useState<Goal[]>(INITIAL_GOALS);

  const handleUpdateGoals = (updatedGoals: Goal[]) => {
    setGoals(updatedGoals);
  };

  const visibleArticles = showAllNews ? NEWS_ARTICLES : NEWS_ARTICLES.slice(0, 3);

  return (
    <div className="space-y-16 pb-16">
      <AnimatePresence>
        {selectedArticle && (
          <NewsModal 
            article={selectedArticle} 
            onClose={() => setSelectedArticle(null)} 
          />
        )}
      </AnimatePresence>
      <header className="space-y-6">
        <div className="flex items-center gap-3 mb-2">
          <div className="h-[1px] w-12 bg-[#D4AF37]"></div>
          <span className="text-base font-black text-[#D4AF37] uppercase tracking-[0.5em]">ORBIT WEALTH PRO — Global Fintech Engine</span>
        </div>
        <h1 className="text-6xl sm:text-7xl md:text-9xl font-display font-medium text-[#f59e0b] tracking-tighter leading-[1.1]">
          Financial <br />
          <span className="text-white/70">Dashboard.</span>
        </h1>
        <p className="text-white/90 max-w-xl text-xl md:text-2xl font-light leading-relaxed">
          Access ORBIT WEALTH PRO's suite of institutional-grade financial tools. 
          Precision engineering for the modern global investor.
        </p>
      </header>

      <WealthIntelligenceBlock goals={goals} />

      <div className="py-2">
         <MarketTicker />
      </div>

      <WealthMilestones goals={goals} onUpdateGoals={handleUpdateGoals} />

      <BlogPreview />

      <section className="space-y-10">
        <div className="flex items-center gap-4">
           <h2 className="text-base font-bold text-slate-100 uppercase tracking-[0.4em]">Integrated Computation Suite</h2>
           <div className="flex-1 h-px bg-white/[0.03]"></div>
        </div>
        
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5 md:gap-6">
          {ALL_CARDS.map((card, idx) => (
            <motion.div
              key={card.path}
              initial={idx < 6 ? { opacity: 1, y: 0 } : { opacity: 0, y: 20 }}
              whileInView={idx >= 6 ? { opacity: 1, y: 0 } : undefined}
              viewport={{ once: true, margin: "-50px" }}
              transition={{ delay: idx < 6 ? 0 : 0.1, duration: 0.4 }}
            >
              <Link 
                to={card.path}
                aria-label={`Open ${card.title}`}
                className="group block p-[15px] md:p-8 bg-white/[0.01] border border-white/[0.04] rounded-[1.5rem] md:rounded-[2rem] hover:bg-white/[0.02] hover:border-[#D4AF37]/30 transition-all duration-700 h-full relative overflow-hidden outline-none focus:bg-white/[0.05]"
              >
                <div className="absolute top-0 right-0 p-4 opacity-0 group-hover:opacity-100 transition-opacity">
                  <ArrowRight className="w-4 h-4 text-[#D4AF37]" />
                </div>
                
                <div className="space-y-6">
                  <div className={`w-10 h-10 rounded-xl flex items-center justify-center border border-white/5 bg-white/[0.02] ${card.color}`}>
                    <card.icon className="w-4 h-4" />
                  </div>
                  
                  <div className="space-y-2">
                    <h3 className="text-3xl font-display font-bold text-white group-hover:text-[#f59e0b] transition-colors duration-500">
                      {card.title}
                    </h3>
                    <p className="text-lg text-slate-100 leading-relaxed font-medium line-clamp-2">
                       {card.description}
                    </p>
                  </div>
                </div>
              </Link>
            </motion.div>
          ))}
        </div>
      </section>

      {/* Global Finance News Section */}
      <section id="news-section" className="space-y-10 pt-16">
        <div className="flex items-center gap-4">
           <h2 className="text-base font-bold text-[#D4AF37] uppercase tracking-[0.4em]">Global Finance News</h2>
           <div className="flex-1 h-px bg-[#D4AF37]/10"></div>
           <div className="flex items-center gap-2 text-base font-bold text-white/70 uppercase tracking-widest">
             <div className="w-1 h-1 rounded-full bg-[#D4AF37] animate-pulse"></div>
             Live Updates
           </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5 md:gap-6">
          {visibleArticles.map((article, idx) => (
            <NewsCard key={idx} article={article} onReadMore={setSelectedArticle} />
          ))}
        </div>
        
        <div className="flex justify-center pt-4">
          <button 
            type="button"
            onClick={() => {
              if (showAllNews) {
                setShowAllNews(false);
                const section = document.getElementById('news-section');
                if (section) {
                  const top = section.getBoundingClientRect().top + window.pageYOffset - 100;
                  window.scrollTo({ top, behavior: 'smooth' });
                }
              } else {
                setShowAllNews(true);
              }
            }}
            className="px-8 py-3 bg-white/[0.02] border border-white/10 rounded-full text-base font-bold text-white/70 uppercase tracking-widest hover:bg-[#f59e0b]/10 hover:border-[#f59e0b]/30 hover:text-white transition-all cursor-pointer inline-flex items-center justify-center"
          >
            {showAllNews ? 'Show Less Insights' : 'Explore All Market Insights'}
          </button>
        </div>
      </section>

      <section className="pt-24 border-t border-white/[0.05] grid grid-cols-1 md:grid-cols-2 gap-12 items-center">
        <div className="space-y-4">
          <h2 className="text-4xl font-display font-medium">Built for accuracy.</h2>
          <p className="text-xl text-slate-100 leading-relaxed max-w-md">
            Our engine accounts for localized interest compounding, tax thresholds, and currency fluctuations to ensure your planning is based on high-integrity data.
          </p>
        </div>
        <div className="flex gap-12">
            <div className="space-y-1 text-center">
              <div className="text-6xl font-display text-white">100%</div>
              <div className="text-base text-slate-300 uppercase font-black tracking-[0.2em]">Computation Accuracy</div>
            </div>
            <div className="space-y-1 text-center">
              <div className="text-6xl font-display text-white">Instant</div>
              <div className="text-base text-slate-300 uppercase font-black tracking-[0.2em]">Execution Latency</div>
            </div>
        </div>
      </section>

      {/* Meet the Founder Section */}
      <section className="bg-slate-900/50 border border-slate-800 rounded-[2rem] p-8 md:p-12 my-12 text-white overflow-hidden relative">
        <div className="absolute top-0 right-0 w-64 h-64 bg-[#F3C64F]/5 rounded-full blur-3xl -mr-32 -mt-32"></div>
        <div className="relative z-10 grid grid-cols-1 md:grid-cols-12 gap-8 items-center">
          <div className="md:col-span-8">
            <h2 className="text-3xl md:text-5xl font-bold text-[#F3C64F] mb-6 flex items-center gap-3">
              <UserCheck className="w-6 h-6" /> Meet the Founder
            </h2>
            <h3 className="text-2xl md:text-4xl font-bold text-white mb-4">Munchangi Matyaraju (mm Raju)</h3>
            <p className="text-lg md:text-2xl text-slate-100 leading-relaxed max-w-2xl font-medium">
              Founder & Chief AI Architect of Orbit Wealth Pro. Committed to building zero-maintenance, 
              highly accurate financial intelligence tools for global investors. Driven by a passion for 
              decentralizing complex wealth metrics through intelligent automation.
            </p>
            <div className="mt-8">
              <a 
                href="https://www.linkedin.com/in/munchangi-matyaraju" 
                target="_blank" 
                rel="noopener noreferrer"
                className="inline-flex items-center gap-2 text-blue-400 hover:text-white hover:bg-blue-400/10 px-4 py-2 rounded-xl transition-all font-bold text-lg"
              >
                🌐 Connect on LinkedIn →
              </a>
            </div>
          </div>
          <div className="md:col-span-4 flex justify-center md:justify-end">
            <div className="w-48 h-48 rounded-full overflow-hidden border-4 border-[#F3C64F] shadow-lg flex-shrink-0 bg-slate-900 relative">
                <img 
                  src="https://i.ibb.co/B5m9W7Dt/founder-jpg.jpg" 
                  alt="Munchangi Matyaraju" 
                  className="w-full h-full object-cover grayscale hover:grayscale-0 transition-all duration-500"
                  loading="lazy"
                  onError={(e) => {
                    e.currentTarget.classList.add('hidden');
                    const fallback = e.currentTarget.nextElementSibling;
                    if (fallback) fallback.classList.remove('hidden');
                  }}
                  referrerPolicy="no-referrer"
                />
                <div className="hidden w-full h-full flex flex-col items-center justify-center animate-pulse">
                  <UserCheck className="w-12 h-12 text-gray-600" />
                  <span className="text-base font-bold text-gray-500 mt-2 uppercase tracking-widest">MM Raju</span>
                </div>
            </div>
          </div>
        </div>
      </section>

      {/* Global Presence Section - Micro-links for targeted regions */}
      <section className="space-y-10 pt-16">
        <div className="flex items-center gap-4">
           <h2 className="text-base font-bold text-white/70 uppercase tracking-[0.4em]">Global Presence</h2>
           <div className="flex-1 h-px bg-white/[0.03]"></div>
        </div>

        <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 gap-4">
          {[
            { id: 'usa', name: 'USA', flag: '🇺🇸' },
            { id: 'uk', name: 'UK', flag: '🇬🇧' },
            { id: 'germany', name: 'Germany', flag: '🇩🇪' },
            { id: 'switzerland', name: 'Switzerland', flag: '🇨🇭' },
            { id: 'norway', name: 'Norway', flag: '🇳🇴' },
            { id: 'sweden', name: 'Sweden', flag: '🇸🇪' },
            { id: 'denmark', name: 'Denmark', flag: '🇩🇰' },
            { id: 'netherlands', name: 'Netherlands', flag: '🇳🇱' },
            { id: 'canada', name: 'Canada', flag: '🇨🇦' },
            { id: 'australia', name: 'Australia', flag: '🇦🇺' },
            { id: 'india', name: 'India', flag: '🇮🇳' },
            { id: 'uae', name: 'UAE', flag: '🇦🇪' }
          ].map((country) => (
            <Link 
              key={country.id}
              to={`/tools/mortgage/${country.id}`}
              className="flex items-center gap-2 p-3 bg-white/[0.02] border border-white/5 rounded-xl hover:border-[#D4AF37]/40 hover:bg-white/[0.04] transition-all group"
            >
              <span className="text-2xl grayscale group-hover:grayscale-0 transition-all">{country.flag}</span>
              <span className="text-base font-bold text-white/70 uppercase tracking-widest group-hover:text-white transition-colors">{country.name}</span>
            </Link>
          ))}
        </div>
      </section>
    </div>
  );
}
