/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React from 'react';
import { Scale, AlertTriangle, CheckCircle2, Info } from 'lucide-react';

export default function Disclaimer() {
  return (
    <div className="max-w-4xl mx-auto space-y-12 py-12 text-white">
      <header className="space-y-4 text-center">
        <div className="inline-flex p-3 bg-amber-500/10 rounded-2xl border border-amber-500/20 mb-4">
           <Scale className="text-amber-500 w-8 h-8" />
        </div>
        <h1 className="text-4xl font-bold tracking-tighter text-white">Financial Disclaimer</h1>
        <p className="text-white/40 text-sm uppercase tracking-widest font-bold">Important Notice to Our Users</p>
      </header>

      <div className="bg-white/[0.02] border border-white/5 rounded-3xl p-8 md:p-12 space-y-8 leading-relaxed text-white/70">
        <div className="p-6 bg-amber-500/10 border border-amber-500/20 rounded-2xl flex items-start gap-4">
           <AlertTriangle className="w-6 h-6 text-amber-500 shrink-0 mt-1" />
           <p className="text-amber-500 font-bold text-lg leading-tight tracking-tight">
             Calculations provided by Orbit Wealth Pro are for informational purposes only and do NOT constitute financial, legal, or tax advice.
           </p>
        </div>

        <section className="space-y-4">
          <div className="flex items-center gap-3 text-white">
            <CheckCircle2 className="w-5 h-5 text-[#0055FF]" />
            <h2 className="text-xl font-bold tracking-tight">Informational Purpose Only</h2>
          </div>
          <p>
            The results generated by our calculators are estimates based on the inputs provided and standard financial formulas. Actual results may vary based on specific institutional policies, market fluctuations, and individual circumstances.
          </p>
        </section>

        <section className="space-y-4">
          <div className="flex items-center gap-3 text-white">
            <Info className="w-5 h-5 text-[#0055FF]" />
            <h2 className="text-xl font-bold tracking-tight">Seek Professional Guidance</h2>
          </div>
          <p>
            We strongly recommend consulting with a certified financial advisor or tax professional before making significant financial decisions based on the outputs of these tools. Financial planning involves risks, and historical performance is not indicative of future results.
          </p>
        </section>

        <section className="space-y-4 border-t border-white/5 pt-8">
          <h2 className="text-xl font-bold text-white tracking-tight">No Liability</h2>
          <p>
            Orbit Wealth Pro and its developers assume no responsibility for any losses or damages resulting from the use of this website or reliance on its content. By using these tools, you acknowledge that you are doing so at your own risk.
          </p>
        </section>
      </div>
    </div>
  );
}
